### ISSUE TITLE
OSError: mysql_config not found

### ISSUE THREAD

**Issue by vikas027** [sethblack/mysql-to-json#3]
Hey,

How can  I solve this?

```# pip3 install mysql-to-json
Collecting mysql-to-json
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/cd/14/2a1eb38a53a8288ad75155f49c9790a4d6de6505c4795b503c8a12cde898/mysql-to-json-1.0.0.tar.gz
Collecting mysqlclient (from mysql-to-json)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/ec/fd/83329b9d3e14f7344d1cb31f128e6dbba70c5975c9e57896815dbb1988ad/mysqlclient-1.3.13.tar.gz (90kB)
    100% |████████████████████████████████| 92kB 3.8MB/s
    Complete output from command python setup.py egg_info:
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ckkav8f5/mysqlclient/setup.py", line 18, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-ckkav8f5/mysqlclient/setup_posix.py", line 53, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-build-ckkav8f5/mysqlclient/setup_posix.py", line 28, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ckkav8f5/mysqlclient/```

**Comment by vikas027** [comment]
Never mind, these are the per-requisites for the pip package on CentOS 7. Maybe add this to your [README.md](https://github.com/sethblack/mysql-to-json/blob/master/README.md)

```
$ sudo yum -y install python34-pip python34-devel python34
```
